name: Upcoming Date Alert

# Run action at midnight on the 25th of each month and allow manual runs
on:
  schedule:
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  check-dates:
    runs-on: ubuntu-latest
    outputs:
      files_content: ${{ steps.get-files.outputs.files_content }}
      upcoming_dates: ${{ steps.regex-match.outputs.matches }}
    steps:
      # Checkout code (version 4)
      - name: Checkout code
        uses: actions/checkout@v4

      # Extract content of Markdown files
      - name: Read Markdown files
        id: get-files
        run: |
          files_content=$(find content/en/docs -name '*.md' -exec cat {} +)
          echo "$files_content"  # Output the content for the subsequent step to capture
        shell: bash

      # Debug: Print upcoming dates to search for
      - name: Debug Print upcoming dates to search for
        run: |
          echo "Upcoming dates to search for:"
          echo "------------------------------"
          echo "Current date: $(date '+%B %d, %Y')"
          echo "First day of upcoming month: $(date -d 'next month' '+%B 1, %Y')"
          echo "Last day of upcoming month: $(date -d 'next month -1 day' '+%B %d, %Y')"
          echo "------------------------------"

      # Perform regex match to find upcoming dates in Markdown files
      - name: Perform regex match
        id: regex-match
        uses: kaisugi/action-regex-match@v1.0.1
        with:
          text: ${{ steps.get-files.outputs.files_content }}
          regex: '(January|February|March|April|May|June|July|August|September|October|November|December)\s+[0-9]{1,2},\s+[0-9]{4}'
          flags: g

      # Debug: Print matched dates
      - name: Debug: Print matched dates
        if: ${{ steps.regex-match.outputs.matches != '' }}  # Check if there are matches
        run: |
          echo "Matched dates found in Markdown files:"
          echo "${{ steps.regex-match.outputs.matches }}"
