name: Upcoming Date Alert

# Run action at midnight on the 25th of each month and allow manual runs
on:
  schedule:
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  check-dates:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code (version 4)
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      # Step 2: Read content of Markdown files and write to a file
      - name: Step 2 - Read Markdown files and write to a file
        run: |
        find content/en/docs -name '*.md' -exec cat {} + > files_content.txt

      # Step 3: Confirm the file is created and contains the content
      - name: Step 3 - Confirm file is created and contains content
        run: |
          cat files_content.txt
