name: Upcoming Date Alert

# Run action at midnight on the 25th of each month
on:
  schedule:
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  check-dates:
    runs-on: ubuntu-latest
    steps:
      # Multiplatform Regex action to search for dates
      - name: Multiplatform Regex
        id: regex
        uses: tilation/regex-on-repo
        with:
          github: ${{ github.repository }}
          ref: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
          regex: '(January|February|March|April|May|June|July|August|September|October|November|December).{0,6} [0-9]{4}'
          file: 'content/en/docs/**/*.md'
          debug: true

      # Process Regex Matches
      - name: Process Regex Matches
        id: process-matches
        run: |
          matches="${{ steps.regex.outputs.matches }}"
          file_content=""
          while IFS= read -r match; do
            # Extract filename, line number, and text containing the match
            # Example format: "filename:line_number:text"
            filename=$(echo "$match" | cut -d ':' -f 1)
            line_number=$(echo "$match" | cut -d ':' -f 2)
            text=$(echo "$match" | cut -d ':' -f 3-)
            file_content="${file_content}\nFile: ${filename}\nLine: ${line_number}\nText: ${text}\n---"
          done <<< "$matches"
          echo "file_content=$file_content"

      # Create GitHub issue based on matches
      - name: Create GitHub issue
        if: ${{ steps.regex.outputs.matches != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: "Upcoming Dates Search: Check if Updates Are Needed"
          BODY: |
            Manually confirm if updates are needed in the following docs:

            ${{ steps.process-matches.outputs.file_content }}

        run: |
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --body "$BODY" \
            --repo "$GH_REPO")
