name: Upcoming Date Alert

# Run action at midnight on the 25th of each month and allow manual runs
on:
  schedule:
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  check-dates:
    runs-on: ubuntu-latest
    env:
      FILES_CONTENT: ""
    steps:
      # Step 1: Checkout code (version 4)
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      # Step 2: Read content of Markdown files and set environment variable
      - name: Step 2 - Read Markdown files and set environment variable
        run: |
          echo "FILES_CONTENT="$(cat content/en/docs/*.md)" >> $GITHUB_ENV
          echo "$FILES_CONTENT"

      # Step 3: Confirm Markdown files content
      - name: Step 3 - Confirm Markdown files content
        run: 
          echo "Content of Markdown files (from environment variable):"
          echo "------------------------------"
          echo "$FILES_CONTENT"
          echo "------------------------------"
          