name: Upcoming Date Alert

on:
  schedule:
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  check-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Scan files for dates
        id: scan
        run: node _scripts/scanDates.js

      - name: Create GitHub issue
        if: steps.scan.outputs.scan_output != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: "Upcoming Dates Search: Check if Updates Are Needed"
          BODY: |
            Manually confirm if updates are needed in the following docs:
            
            ${{ join(steps.scan.outputs.scan_output, '\n') }}
        run: |
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --body "$BODY" \
            --repo "$GH_REPO")
