name: Upcoming Date Alert

on:
  schedule:
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  check-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Scan files for dates
        run: node scanDates.js

      - name: Create GitHub issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: "Upcoming Dates Search: Check if Updates Are Needed"
          BODY: |
            if [[ -n "${{ steps.check-dates.outputs.scan_output }}" ]]; then
              echo "Manually confirm if updates are needed in the following docs:\n\n${{ steps.check-dates.outputs.scan_output }}"
            else
              echo "Ran successfully. No upcoming dates found for the next month."
            fi
        run: |
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --body "$BODY" \
            --repo "$GH_REPO")
