name: Upcoming Date Alert

# Run action at midnight on the 25th of each month and allow manual runs
on:
  schedule:
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  check-dates:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code (version 4)
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      # Step 2: Read content of Markdown files and set environment variable
      - name: Step 2 - Read Markdown files and set environment variable
        run: |
          echo "FILES_CONTENT=$(find content/en/docs -name '*.md' -exec cat {} +)" >> $GITHUB_ENV
          echo "$FILES_CONTENT"

      # Step 3: Confirm the environment variable is set
      - name: Step 3 - Confirm environment variable is set
        run: echo "$FILES_CONTENT"
