name: Spellcheck Action

on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Get the list of changed Markdown files in docs/content/en/docs/
    - name: Get changed Markdown files
      id: get_changed_md_files
      run: |
        git fetch origin
        CHANGED_MD_FILES=$(git diff --name-only HEAD^ HEAD | grep '^docs/content/en/docs/.*\.md$' || true)
        echo "CHANGED_MD_FILES=${CHANGED_MD_FILES}" >> $GITHUB_ENV

    # Step 3: Run spellcheck on changed Markdown files
    - name: Spellcheck
      if: env.CHANGED_MD_FILES != ''
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        files: ${{ env.CHANGED_MD_FILES }}
